// Writes config/abi.ts from the Foundry build, so the server and app use the
// exact ABI the contracts were compiled with. Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";

const out = new URL("../contracts/out/", import.meta.url);
const read = (file, name) => {
  try {
    return JSON.parse(readFileSync(new URL(`${file}/${name}.json`, out))).abi;
  } catch {
    console.warn(`skipped ${file}/${name} (not built yet)`);
    return null;
  }
};

const abis = {
  junoFactoryAbi: read("IJuno.sol", "IJunoFactory"),
  junoCurveAbi: read("IJuno.sol", "IJunoCurve"),
  curveMathAbi: read("IJuno.sol", "ICurveMath"),
  junoTokenAbi: read("JunoToken.sol", "JunoToken"),
  mockAggregatorAbi: read("MockAggregator.sol", "MockAggregator"),
  testUsdcAbi: read("TestUSDC.sol", "TestUSDC"),
};

let ts = "// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit.\n\n";
for (const [name, abi] of Object.entries(abis)) {
  if (!abi) continue;
  ts += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(new URL("../config/abi.ts", import.meta.url), ts);
console.log("config/abi.ts:", Object.keys(abis).join(", "));
